export default {
    'dia-0': {value: 'domingo'},
    'dia-1': {value: 'lunes'},
    'dia-2': {value: 'martes'},
    'dia-3': {value: 'miércoles'},
    'dia-4': {value: 'jueves'},
    'dia-5': {value: 'viernes'},
    'dia-6': {value: 'sábado'},
    'son-las': {value: 'Son las'},
    'es-la': {value: 'Es la'},
    'mañana': {value: 'mañana', pre: 'de la'},
    'mediadia': {value: 'mediadia', pre: 'del'},
    'madrugada': {value: 'madrugada', pre: 'de la'},
    'tarde': {value: 'tarde', pre: 'de la'},
    'noche': {value: 'noche', pre: 'de la'},
    'punto': {value: 'en punto'},
    'con': {value: 'con'},
    'y': {value: 'y'},
    0: {value: 'cero'},
    1: {value: 'una'},
    2: {value: 'dos'},
    3: {value: 'tres'},
    4: {value: 'cuatro'},
    5: {value: 'cinco'},
    6: {value: 'seis'},
    7: {value: 'siete'},
    8: {value: 'ocho'},
    9: {value: 'nueve'},
    10: {value: 'diez'},
    11: {value: 'once'},
    12: {value: 'doce'},
    13: {value: 'trece'},
    14: {value: 'catorce'},
    15: {value: 'quince'},
    16: {value: 'dieciséis'},
    20: {value: 'veinte'},
    22: {value: 'veintidós'},
    23: {value: 'veintitrés'},
    26: {value: 'veintiséis'},
    30: {value: 'treinta'},
    40: {value: 'cuarenta'},
    50: {value: 'cincuenta'},
    'dieci': {value: 'dieci'},
    'veinti': {value: 'vinti'},
};
