export const horasStringList = {
    0: {value: 'domingo'},
    1: {value: 'lunes'},
    2: {value: 'martes'},
    3: {value: 'miércoles'},
    4: {value: 'jueves'},
    5: {value: 'viernes'},
    6: {value: 'sábado'},
    'Son las': {value: 'Son las'},
    'Es la': {value: 'Es la'},
    'de la mañana': {value: 'de la mañana'},
    'del mediadia': {value: 'del mediadia'},
    'de la madrugada': {value: 'madrugada'},
    'de la tarde': {value: 'de la tarde'},
    'de la noche': {value: 'de la noche'},
    'en punto': {value: 'en punto'},
    'con': {value: 'con'},
    'y': {value: 'y'},
}

export const numerosStringList = {
    0: {value: 'cero'},
    1: {value: 'una'},
    2: {value: 'dos'},
    3: {value: 'tres'},
    4: {value: 'cuatro'},
    5: {value: 'cinco'},
    6: {value: 'seis'},
    7: {value: 'siete'},
    8: {value: 'ocho'},
    9: {value: 'nueve'},
    10: {value: 'diez'},
    11: {value: 'once'},
    12: {value: 'doce'},
    13: {value: 'trece'},
    14: {value: 'catorce'},
    15: {value: 'quince'},
    16: {value: 'dieciséis'},
    20: {value: 'veinte'},
    22: {value: 'veintidós'},
    23: {value: 'veintitrés'},
    26: {value: 'veintiséis'},
    30: {value: 'treinta'},
    40: {value: 'cuarenta'},
    50: {value: 'cincuenta'},
    60: {value: 'sesenta'},
    'dieci': {value: 'dieci'},
    'veinti': {value: 'vinti'},
};
