export default {
    'day-0': {value: 'воскресенье'},
    'day-1': {value: 'понедельник'},
    'day-2': {value: 'вторник'},
    'day-3': {value: 'среда'},
    'day-4': {value: 'четверг'},
    'day-5': {value: 'пятница'},
    'day-6': {value: 'суббота'},
    'morning': {value: 'утра'},
    'day': {value: 'дня'},
    'evening': {value: 'вечера'},
    'night': {value: 'ночи'},
    'hours': {value: 'часов', value2: 'часа', single: 'час'},
    'minutes': {value: 'минут', value2: 'минуты', single: 'минута'},
    0: {value: 'ноль', minutes: 'ноль ноль'},
    1: {value: 'один', minutes: 'одна', hour: 'час'},
    2: {value: 'два', minutes: 'две'},
    3: {value: 'три'},
    4: {value: 'четыре'},
    5: {value: 'пять'},
    6: {value: 'шесть'},
    7: {value: 'семь'},
    8: {value: 'восемь'},
    9: {value: 'девять'},
    10: {value: 'десять'},
    11: {value: 'одиннадцать'},
    12: {value: 'двенадцать'},
    13: {value: 'тринадцать'},
    14: {value: 'четырнадцать'},
    15: {value: 'пятнадцать'},
    16: {value: 'шестнадцать'},
    17: {value: 'семнадцать'},
    18: {value: 'восемнадцать'},
    19: {value: 'девятнадцать'},
    20: {value: 'двадцать'},
    30: {value: 'тридцать'},
    40: {value: 'сорок'},
    50: {value: 'пятьдесят'},
};
